# Generated by Django 6.0 on 2025-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='makeup_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='skin_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='skincare_recommendation',
            field=models.TextField(blank=True),
        ),
    ]
